src/Entity/Reglement/Avoir.php
<?php

namespace App\Entity\Reglement;

use App\Entity\Admin\LigneCompta;
use App\Entity\Admin\Tiers;
use App\Library\AsLetter;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Vente\Facture;
use Exception;

/**
 * Avoir
 *
 * @ORM\Table(name="avoir")
 * @ORM\Entity(repositoryClass="App\Repository\Reglement\AvoirRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Avoir
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="reference", type="string", nullable=true)
     */
    private $reference;

    /**
     * @var Tiers
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Tiers")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     */
    private $client;

    /**
     * @var float
     *
     * @ORM\Column(name="montant", type="float")
     */
    private $montant;

    /**
     * @var Facture
     * @ORM\ManyToOne(targetEntity="App\Entity\Vente\Facture")
     * @ORM\JoinColumn(name="facture_id", referencedColumnName="id")
     */
    private $facture;

    /**
     * @var bool
     *
     * @ORM\Column(name="payed", type="boolean")
     */
    private $payed = false;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\Reglement\InfoVente", cascade={"persist","remove"})
     * @ORM\JoinTable(name="avoir_info_vente",
     *      joinColumns={@ORM\JoinColumn(name="avoir_id", referencedColumnName="id", onDelete="CASCADE")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="info_vente_id", referencedColumnName="id", unique=true, onDelete="CASCADE")}
     *      )
     */
    private $ventes;

    /**
     * @var DateTime
     * @ORM\Column(name="date_avoir", type="date")
     */
    private $dateAvoir;



    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set montant
     *
     * @param float $montant
     *
     * @return Avoir
     */
    public function setMontant($montant)
    {
        $this->montant = $montant;

        return $this;
    }

    /**
     * Get montant
     *
     * @return float
     */
    public function getMontant()
    {
        return $this->montant;
    }

    /**
     * Set payed
     *
     * @param boolean $payed
     *
     * @return Avoir
     */
    public function setPayed($payed)
    {
        $this->payed = $payed;

        return $this;
    }

    /**
     * Get payed
     *
     * @return bool
     */
    public function getPayed()
    {
        return $this->payed;
    }

    /**
     * Set client
     *
     * @param Tiers $client
     *
     * @return Avoir
     */
    public function setClient(Tiers $client = null)
    {
        $this->client = $client;

        return $this;
    }


    /**
     * @param string $refFacture
     * @return Avoir
     */
    public function setRefFacture($refFacture)
    {
        $this->refFacture = $refFacture;
        return $this;
    }

    /**
     * @param Facture $facture
     * @return array
     * @throws Exception
     */
    public function getLignes(Facture $facture)
    {
        $lignes = array();
        $detail = 'REMBOURSEMENT ';
        if($this->getClient()->getType() == 'personne'){
            $detail = $detail.'PART '.$facture->getReference().' '.$this->getClient();
        } else {
            $detail = $this->getClient().' '.$facture->getReference();
        }

        $code_journal = 'VTE AV';

        $ligne1 = new LigneCompta();
        $ligne1->setCodeJournal($code_journal);
        $ligne1->setRefFact($this->getReference());
        $ligne1->setDateLigne(new DateTime());
        $ligne1->setNumCmpt($facture->getTier()->getNumCompte());
        $ligne1->setMntCredit((int)$this->getMontant());
        $ligne1->setDetail($detail);
        $ligne1->setRefAvoir($this->getReference());
        $lignes[] = $ligne1;


        /** @var InfoVente $item */
        foreach ($this->getVentes()->getIterator() as $item){
            $ligne = new LigneCompta();
            $ligne->setCodeJournal($code_journal);
            $ligne->setRefFact($this->getReference());
            $ligne->setDateLigne(new DateTime());
            $ligne->setNumCmpt($item->getCompteCie());
            $ligne->setMntDebit((int)$item->getMontant());
            $ligne->setDetail($detail);
            $ligne->setRefAvoir($this->getReference());
            $lignes[] = $ligne;
        }

        return $lignes;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }

    /**
     * Get client
     *
     * @return Tiers
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Add vente
     *
     * @param InfoVente $vente
     *
     * @return Avoir
     */
    public function addVente(InfoVente $vente)
    {
        $this->ventes[] = $vente;

        return $this;
    }

    /**
     * Remove vente
     *
     * @param InfoVente $vente
     */
    public function removeVente(InfoVente $vente)
    {
        $this->ventes->removeElement($vente);
    }

    /**
     * Get ventes
     *
     * @return Collection
     */
    public function getVentes()
    {
        return $this->ventes;
    }

    /**
     * @return $this
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function faireMontant()
    {
        $total = 0;
        foreach ($this->ventes->getIterator() as $item){
            $total = $total + $item->getMontant();
        }
        $this->setMontant($total);
        return $this;
    }

    public function getCieVente()
    {
        $elements = $this->ventes->toArray();
        $total = '';
        $i = 0;
        $len = count($elements);
        foreach ($elements as $item){
            $total = $total.$item->getCieName();
            if ($i != $len - 1) {
                $total = $total.'/';
            }
            $i++;
        }
        return $total;
    }

    /**
     * @return DateTime
     */
    public function getDateAvoir()
    {
        return $this->dateAvoir;
    }

    /**
     * @param DateTime $dateAvoir
     * @return Avoir
     */
    public function setDateAvoir($dateAvoir)
    {
        $this->dateAvoir = $dateAvoir;
        return $this;
    }

    /**
     * @ORM\PrePersist()
     *
     * @throws Exception
     */
    public function faireDateAvoir()
    {
        $this->setDateAvoir(new DateTime());
    }

    public function __toString()
    {
        return strval($this->getMontant()).' MGA du '.$this->getDateAvoir()->format('d/m/Y');
    }

    /**
     * Set facture
     *
     * @param Facture $facture
     *
     * @return Avoir
     */
    public function setFacture(Facture $facture = null)
    {
        $this->facture = $facture;

        return $this;
    }

    /**
     * Get facture
     *
     * @return Facture
     */
    public function getFacture()
    {
        return $this->facture;
    }

    /**
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @param string $reference
     * @return Avoir
     */
    public function setReference($reference)
    {
        $this->reference = $reference;
        return $this;
    }

    public function setCieVente()
    {
        foreach ($this->ventes->getIterator() as $item){
            $item->setNameCie($item->getCieName());
        }
    }

    public function getLetter()
    {
        $text = AsLetter::asLetters($this->getMontant());
        $text_explode = explode(' ', $text);
        if ($text_explode[0] == 'millions'){
            $text = 'un '.$text;
        }
        return $text;
    }
}

src/Form/Reglement/AvoirType.php
<?php

namespace App\Form\Reglement;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvoirType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ventes', CollectionType::class, [
                'entry_type'   => InfoVenteType::class,
                'allow_add' => false,
                'allow_delete' => false,
                'prototype' => false,
                'attr' => array(
                    'class' => 'my-selector',
                ),
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Reglement\Avoir'
        ));
    }
}

src/Controller/Etat/AvoirController.php
<?php

namespace App\Controller\Etat;

use App\Controller\BaseController;
use App\Repository\Admin\TiersRepository;
use App\Repository\Reglement\AvoirRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class AvoirController
 * @package App\Controller\Etat
 *
 * @Route("/avoir")
 */
class AvoirController extends BaseController
{
    /**
     * Lists all Avoir entities.
     *
     * @Route("/", name="etat_avoir_index")
     *
     * @param TiersRepository $tiersRepository
     *
     * @return Response
     */
    public function index(TiersRepository $tiersRepository)
    {
        $clients = $tiersRepository->findBy(
            ['discriminator' => 'client'],
            ['raisonSociale' => 'ASC', 'nom' => 'ASC']
        );

        return $this->render('etat/avoir/index.html.twig', array(
            'clients' => $clients,
        ));
    }

    /**
     * Liste avoir
     *
     * @Route("/list/{etat}/{id_cli}/{debut}/{fin}",
     *     name="etat_avoir_list",
     *     defaults={
     *     "id_cli" = 0,
     *     "debut" = 0,
     *     "fin" = 0
     *     })
     *
     * @param $etat
     * @param $id_cli
     * @param $debut
     * @param $fin
     * @param AvoirRepository $avoirRepository
     *
     * @return Response
     */
    public function list($etat , $id_cli, $debut, $fin, AvoirRepository $avoirRepository)
    {
        $state = ($etat == 'payee')?true:false;
        $avoirs = $avoirRepository->getByEtaTCliPeriode($state, $id_cli, $debut, $fin);
        return $this->render('etat/avoir/list.html.twig', [
            'avoirs' => $avoirs,
            'id_cli' => (int)$id_cli,
            'etat'   => $etat
        ]);
    }
}

src/Controller/Reglement/AvoirController.php
<?php

namespace App\Controller\Reglement;


use App\Controller\BaseController;
use App\Entity\Logs;
use App\Form\Reglement\AvoirType;
use App\Entity\Reglement\Avoir;
use App\Manager\LogsManager;
use App\Repository\Admin\LigneComptaRepository;
use App\Repository\Admin\TiersRepository;
use App\Repository\Reglement\AvoirRepository;
use Exception;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class AvoirController
 * @package App\Controller\Reglement
 *
 * @Route("/avoir")
 */
class AvoirController extends BaseController
{
    /**
     * @var AvoirRepository
     */
    private $repository;

    /**
     * AvoirController constructor.
     *
     * @param PaginatorInterface $paginator
     * @param Pdf $pdf
     * @param AvoirRepository $repository
     * @param LogsManager $logsManager
     */
    public function __construct(
        PaginatorInterface $paginator,
        Pdf $pdf,
        AvoirRepository $repository,
        LogsManager $logsManager
    ) {
        parent::__construct($paginator, $pdf, $logsManager);
        $this->repository = $repository;
    }

    /**
     * Index of avoir
     *
     * @Route("/", name="avoir_index")
     *
     * @param TiersRepository $tiersRepository
     *
     * @return Response
     */
    public function index(TiersRepository $tiersRepository)
    {
        $clients = $tiersRepository->findBy(['discriminator' => 'client'], ['raisonSociale' => 'ASC', 'nom' => 'ASC']);

        return $this->render(
            'reglement/avoir/index.html.twig',
            [
                'clients' => $clients,
            ]
        );
    }

    /**
     * List avoir
     *
     * @Route("/list/{etat}/{id_cli}/{debut}/{fin}",
     *     name="avoir_list_etat",
     *     defaults={
     *     "id_cli" = "0",
     *     "debut" = "0",
     *     "fin" = "0"
     * })
     *
     * @param $etat
     * @param $id_cli
     * @param $debut
     * @param $fin
     *
     * @return Response
     */
    public function listAction($etat, $id_cli, $debut, $fin)
    {
        $em = $this->getDoctrine()->getManager();
        $state = ($etat == 'payee') ? true : false;
        $avoirs = $this->repository->getByEtaTCliPeriode($state, $id_cli, $debut, $fin);

        return $this->render(
            'reglement/avoir/list.html.twig',
            [
                'avoirs' => $avoirs,
                'id_cli' => (int)$id_cli,
                'etat' => $etat,
            ]
        );
    }

    /**
     * Finds and displays a Avoir entity.
     *
     * @Route("/{id}/show", name="avoir_show")
     *
     * @param Request $request
     * @param Avoir $avoir
     *
     * @return Response
     */
    public function showAction(Request $request, Avoir $avoir)
    {
        $form = $this->createAvoirForm($avoir);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $avoir->setPayed(true);
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            $data = [];
            $data['cible'] = "#paye";

            return new Response(json_encode($data), 201, ['Content-Type' => 'application/json']);
        }

        return $this->render(
            'confirm.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Edit Avoir
     *
     * @Route("/{id}/edit", name="avoir_modif")
     *
     * @param Request $request
     * @param Avoir $avoir
     * @param LigneComptaRepository $comptaRepository
     *
     * @return Response
     * @throws Exception
     */
    public function modifAction(Request $request, Avoir $avoir, LigneComptaRepository $comptaRepository)
    {
        $avoir->setCieVente();
        $form = $this->createForm(
            AvoirType::class,
            $avoir,
            [
                'action' => $this->generateUrl('avoir_modif', ['id' => $avoir->getId()]),
            ]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $avoir->faireMontant();
            $em->persist($avoir);
            $em->flush();
            $lignes = $comptaRepository->findBy(['refAvoir' => $avoir->getReference()]);

            foreach ($lignes as $ligne) {
                /*$ligne->set*/
                if ($ligne->getMntCredit() == 0) {
                    $ligne->setMntDebit($avoir->getMontant());
                } else {
                    $ligne->setMntCredit($avoir->getMontant());
                }
                $em->flush();
            }

            $facture = $avoir->getFacture();
            $facture->setMontatRembourse($avoir->getMontant());
            $em->persist($facture);
            $em->flush();
            $logs = new Logs();
            $logs->setDescription(
                sprintf(
                    "Modification de l'avoir ref : %s",
                    $avoir->getReference()
                )
            );

            $logs->setUser($this->getUser());
            $this->logsManager->save($logs);

            $data = [];
            $data['cible'] = ($avoir->getPayed()) ? "#paye" : "#non-paye";

            return new Response(json_encode($data), 201, ['Content-Type' => 'application/json']);
        }

        return $this->render(
            'facture/avoir.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Print pdf avoir
     *
     * @Route("/{id}/print-pdf", name="avoir_pdf_print")
     *
     * @param Avoir $avoir
     *
     * @param TiersRepository $tiersRepository
     *
     * @return Response
     */
    public function pdfAction(Avoir $avoir, TiersRepository $tiersRepository)
    {
        $ets = $tiersRepository->find(1);
        $filename = sprintf('avoir-%s.pdf', $avoir->getClient());
        $html = $this->renderView(
            'reglement/avoir/avoir.html.twig',
            [
                'avoir' => $avoir,
                'ets' => $ets,
            ]
        );

        $footer = $this->renderView(
            'footer.html.twig',
            [
                'ets' => $ets,
            ]
        );

        return new Response(
            $this->pdf->getOutputFromHtml($html, ['footer-html' => $footer]),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => sprintf('attachment; filename="%s"', $filename),
            ]
        );
    }

    /**
     * @param Avoir $avoir
     *
     * @return FormInterface The form
     */
    public function createAvoirForm(Avoir $avoir)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('avoir_show', ['id' => $avoir->getId()]))
            ->setMethod('POST')
            ->getForm();
    }
}

templates/reglement/avoir/avoir.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}GESTI{% endblock %}</title>
    {% block stylesheets %}
        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="{{ 'http://statics.com/gesti/css/bootstrap.min.css' }}"/>
        <link rel="stylesheet" href="{{ 'http://statics.com/gesti/css/font-awesome.css' }}" type="text/css"/>

        <!-- page specific plugin styles -->

        <!-- text fonts -->

    {% endblock %}
    <style>
        hr.red{
            display: block;
            height: 1px;
            border: 0;
            border-top: 3px solid #8F0416;
            margin: 1em 0;
            padding: 0;
        }

        hr.separator{
            display: block;
            border: 0;
            border-top: 1px solid #555;
            padding: 0;
            margin-top: 5px;
            margin-bottom: 5px;
        }
    </style>

</head>
<body style="font-size: 15px; padding-top: 15px;">

<div class="container">
    <div class="row text-center">
        <img height="100" alt="Domain Owner's Avatar"
             {% if ets.logo is null %}src="{{ 'http://statics.com/gesti/img/images.png' }}"{% else %} src="{{ 'http://statics.com/gesti/img_upload/'~ets.logo.filename }}"{% endif %} />
        <hr class="red">
    </div>
    <div class="row">
        <div class="col-sm-5" style="float: left">
            <p class="text-center">EDEN GALLERY - Enceinte hotel Ibis</p>
            <p class="text-center">Rue Ravoninahitriniarivo Ankorondrano</p>
            <p class="text-center">ANTANANARIVO 101 -Madagascar</p>
            <p class="text-center">Tel / Fax : (+261) 20 23 640 53</p>
            <p class="text-center">E-mail : <a href="contact@hsmvoyages.com">contact@hsmvoyages.com</a></p>
        </div>
        <div class="col-sm-offset-2 col-sm-5" style="float: right">
            <div class="row">
                <p class="text-center">Antananarivo , {{ avoir.dateAvoir|date('d M Y') }}</p>
            </div>
            <div class="row" style="">
                <p class="">{{'Doit  : '~avoir.client }}</p>
                <p class="">{{ avoir.client.adresse }}</p>
                <p class="">{{'STAT  : '~avoir.client.numStat }}</p>
                <p class="">{{ 'NIF   : '~avoir.client.numNIF }}</p>
            </div>
        </div>
    </div>
    <div class="row">
        <p style="padding: 15px">{{ 'AVOIR : '~avoir.reference }}</p>

    </div>
    <div class="row" style="padding: 15px !important;">
        <table class="table  table-bordered" style="font-size: 12px">
            <thead>
            <tr>
                <th width="15%">Numero billet</th>
                <th width="20%">Passager</th>
                <th width="15%">Montant</th>
            </tr>
            </thead>
            <tbody>
            {% for vente in avoir.ventes %}
                <tr>
                    <td>
                        {{ vente.ticketNumber }}
                    </td>
                    <td>
                        {{ vente.passager }}
                    </td>
                    <td>
                        {{ 'MGA '~vente.montant|number_format(0,',',' ') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row" style="padding: 15px !important;">
        <div class="col-sm-offset-8 col-sm-4">
            <table class="table  table-bordered" style="font-size: 12px">
                <tbody>
                <tr>
                    <td>
                        TOTAL
                    </td>
                    {#{{ facture.montantTva }}
                    {{ facture.totalMontant }}#}
                    <td>
                        {{ 'MGA '~avoir.montant|number_format(0,',',' ') }}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            Arrêté la présente avoir à la somme de:&nbsp; {{ avoir.letter|upper }}&nbsp;ARIARY
        </div>
    </div>

</div>


</body>
</html>

templates/reglement/avoir/index.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if label == "danger" %}
            <script>
                $.notify({
                    // options
                    message: '{{ message }}'
                },{
                    // settings
                    type: '{{ label }}'
                });
            </script>
        {% endif %}
        {#<div class="flash-{{ label }}">
            {{ message }}
        </div>#}
    {% endfor %}
{% endfor %}

<div class="row">
    <div class="col-sm-4">
        <h3><span class="ace-icon fa fa-dollar"></span>&nbsp;Les Avoirs</h3>
    </div>
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-6 text-right" style="padding-top: 20px">
                <div class="form-group">
                    <label for="client" class="col-sm-3 control-label" style="padding-top: 5px">Période</label>
                    <div class="col-sm-9">
                        <select id="periode" class="form-control">
                            <option value="week"  >Cette semaine</option>
                            <option value="last_week"  >Semaine dernière</option>
                            <option value="month"  >Ce mois</option>
                            <option value="last_month"  >Mois dernier</option>
                            <option value="perso"  >Personaliser</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 text-right" style="padding-top: 20px">
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="" style="padding-top: 5px"><strong>Clients:</strong></label>
                    <div class="col-sm-9">
                        <select class="form-control select2" name="" id="cli_id">
                            <option value="0">Tous</option>
                            {% for client in clients %}
                                <option value="{{ client.id }}"> {{ client }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" id="date-perso" style="display: none; margin-top: 10px; margin-right: 13px !important;">
            <div class="col-sm-5">
                <div class="from-group">
                    <label for="" class="col-sm-3 control-label">Debut:</label>
                    <div class="col-sm-9">
                        <input type="date" value="{{ 'now'|date('Y-m-d') }}" class="form-control date" name="" id="Debut">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="from-group">
                    <label for="" class="col-sm-3 control-label">Fin:</label>
                    <div class="col-sm-9">
                        <input type="date" value="{{ 'now'|date('Y-m-d') }}" class="form-control date" name="" id="Fin">
                    </div>
                </div>
            </div>
            <div class="col-sm-1">
                <button class="btn btn-default" id="findByPerso" >
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<ul class="nav nav-tabs padding-12 tab-color-blue" id="myTab">
    <li class="onglet3" id="non-paye" data-cible="#liste-facture">
        <a href="{{ path('avoir_list_etat', {'etat': 'non-paye' }) }}">Non Reglée</a>
    </li>
    <li class="onglet3" id="paye" data-cible="#liste-facture">
        <a href="{{ path('avoir_list_etat', {'etat': 'payee' }) }}">Payée</a>
    </li>
</ul>
<div class="tab-content" id="liste-facture">

</div>

<script>

    $('.onglet3').first().trigger('click');
    $('.select2').css({ width: "100%" }).select2();
</script>

templates/reglement/avoir/list.html.twig

{% if avoirs %}
<table class="table table-bordered table-hover table-stripped">
    <thead>
    <tr>
        {% if id_cli == 0 %}
        <th>Client</th>
        {% endif %}
        <th>Reference</th>
        <th>Date</th>
        <th>Montant</th>
        <th>Les compagnies aériennes</th>
        <th class="text-right">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for avoir in avoirs %}
        <tr>
            {% if id_cli == 0 %}
            <td>{{ avoir.client }}</td>
            {% endif %}
            <td>{{ avoir.reference }}</td>
            <td>{{ avoir.dateAvoir|date('d/m/Y') }}</td>
            <td>{{ 'MGA '~avoir.montant }}</td>
            <td>{{ avoir.cieVente }}</td>
            <td class="text-right">
                <button data-lien="{{ path('avoir_modif', {'id': avoir.id}) }}" class="btn btn-xs btn-purple ajout" data-formTitle="Modifier un avoir" data-mod="#gen_md">
                    <i class="ace-icon fa fa-check-square bigger-120"></i>
                    Modifier
                </button>
                {% if etat == 'non-paye' %}
                <button data-lien="{{ path('avoir_show', {'id': avoir.id}) }}" class="btn btn-xs btn-info ajout" data-formTitle="Regler l'avoir" data-mod="#gen_md">
                    <i class="ace-icon fa fa-check-square bigger-120"></i>
                    Régler
                </button>
                {% endif %}
                <a target="_blank" href="{{ path('avoir_pdf_print', {'id': avoir.id}) }}" class="btn btn-xs btn-danger">
                    <i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
                    Imprimer
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <div class="alert alert-warning text-center">
        Il n'y a pas d'avoir.
    </div>
{% endif %}


templates/reglement/avoir/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Avoir</h1>

    <table>
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avoir.id }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ avoir.montant }}</td>
            </tr>
            <tr>
                <th>Payed</th>
                <td>{% if entity.payed %}Yes{% else %}No{% endif %}</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('avoir_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}