src/Entity/Vente/Facture.php
<?php
/**
 * Created by PhpStorm.
 * User: DEV
 * Date: 04/09/2017
 * Time: 06:19
 */

namespace App\Entity\Vente;

use App\Entity\Admin\Tiers;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;

/**
 * Parcour
 *
 * @ORM\Table(name="facture")
 * @ORM\Entity(repositoryClass="App\Repository\Vente\FactureRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Facture
{
    use FactureTrait;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="reference", type="string", nullable=true)
     */
    private $reference;

    /**
     * @var Tiers
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Tiers")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     */
    private $tier;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Vente\Vente", mappedBy="facture", cascade={"remove"})
     */
    private $ventes;

    private $id_li;

    /**
     * @var string
     *
     * @ORM\Column(name="type_paiement", type="string")
     */
    private $typePaiement;

    /**
     * @var float
     * @ORM\Column(name="montat_rembourse", nullable=true, type="float")
     */
    private $montatRembourse = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="change_taux", type="string", nullable=true)
     */
    private $tauxChange;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_tva", type="float")
     */
    private $montantTva;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="date_echeance", type="date", nullable=true)
     */
    private $dateEcheance;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_transport", type="string")
     *
     */
    private $montantTransport;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_taxe", type="string")
     */
    private $montantTaxe;

    /**
     * @var string
     *
     * @ORM\Column(name="montant_fees", type="string")
     */
    private $montantFees;

    /**
     * @var Scan
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Vente\Scan", cascade={"persist","remove"})
     * @ORM\JoinColumn(name="file_scan_id", referencedColumnName="id")
     */
    private $scan;

    /**
     * @var boolean
     *
     * @ORM\Column(name="payed", type="boolean")
     */
    private $payed = false;

    /**
     * @var bool
     *
     * @ORM\Column(name="annule", type="boolean")
     */
    private $annule = false;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="date_facture", type="date")
     */
    private $dateFacture;

    /**
     * @var float
     * @ORM\Column(name="autre_prod", type="float")
     */
    private $autreProd = 0;

    private $file_scan;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vente\PaiementFacture", mappedBy="facture", orphanRemoval=true)
     */
    private $paiementFactures;

    /**
     * @return mixed
     */
    public function getFileScan()
    {
        return $this->file_scan;
    }

    /**
     * @param mixed $file_scan
     * @return Facture
     */
    public function setFileScan($file_scan)
    {
        $this->file_scan = $file_scan;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set reference
     *
     * @param string $reference
     *
     * @return Facture
     */
    public function setReference($reference)
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * Get reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Set change
     *
     * @param string $change
     *
     * @return Facture
     */
    public function setTauxChange($change)
    {
        $this->tauxChange = $change;

        return $this;
    }

    /**
     * Get tauxChange
     *
     * @return string
     */
    public function getTauxChange()
    {
        return $this->tauxChange;
    }

    /**
     * @return string
     */
    public function getMontantTva()
    {
        return $this->montantTva;
    }

    /**
     * @param string $montantTva
     * @return Facture
     */
    public function setMontantTva($montantTva)
    {
        $this->montantTva = $montantTva;
        return $this;
    }

    /**
     * @param string $typePaiement
     * @return $this
     */
    public function setTypePaiement($typePaiement)
    {
        $this->typePaiement = $typePaiement;
        return $this;
    }

    /**
     * @return string
     */
    public function getTypePaiement()
    {
        return $this->typePaiement;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        //$this->paiements = new ArrayCollection();
        $this->ventes = new ArrayCollection();
        $this->paiementFactures = new ArrayCollection();
    }

    /**
     * @return DateTime
     */
    public function getDateEcheance()
    {
        return $this->dateEcheance;
    }

    /**
     * @param DateTime $dateEcheance
     * @return Facture
     */
    public function setDateEcheance($dateEcheance)
    {
        $this->dateEcheance = $dateEcheance;
        return $this;
    }

    /**
     * @return string
     */
    public function getMontantTransport()
    {
        return $this->montantTransport;
    }

    /**
     * @param string $montantTransport
     * @return Facture
     */
    public function setMontantTransport($montantTransport)
    {
        $this->montantTransport = $montantTransport;
        return $this;
    }

    /**
     * @return string
     */
    public function getMontantTaxe()
    {
        return $this->montantTaxe;
    }

    /**
     * @param string $montantTaxe
     * @return Facture
     */
    public function setMontantTaxe($montantTaxe)
    {
        $this->montantTaxe = $montantTaxe;
        return $this;
    }

    /**
     * @return string
     */
    public function getMontantFees()
    {
        return $this->montantFees;
    }

    /**
     * @param string $montantFees
     * @return Facture
     */
    public function setMontantFees($montantFees)
    {
        $this->montantFees = $montantFees;
        return $this;
    }


    /**
     * Set payed
     *
     * @param boolean $payed
     *
     * @return Facture
     */
    public function setPayed($payed)
    {
        $this->payed = $payed;

        return $this;
    }

    /**
     * Get payed
     *
     * @return boolean
     */
    public function isPayed()
    {
        return $this->payed;
    }

    /**
     * @return bool
     */
    public function isAnnule()
    {
        return $this->annule;
    }

    /**
     * @param bool $annule
     * @return Facture
     */
    public function setAnnule($annule)
    {
        $this->annule = $annule;
        return $this;
    }

    /**
     * @return DateTime
     */
    public function getDateFacture()
    {
        return $this->dateFacture;
    }

    /**
     * @param DateTime $dateFacture
     * @return Facture
     */
    public function setDateFacture($dateFacture)
    {
        $this->dateFacture = $dateFacture;
        return $this;
    }

    /**
     * @param ArrayCollection $paiements
     */
    public function setPaiements($paiements)
    {
        $this->paiements = $paiements;
    }

    /**
     * @ORM\PrePersist()
     * @throws Exception
     */
    public function makedateFacture()
    {
        $this->dateFacture = new DateTime('now');
    }

    /**
     * Set tier
     *
     * @param Tiers $tier
     *
     * @return Facture
     */
    public function setTier(Tiers $tier = null)
    {
        $this->tier = $tier;

        return $this;
    }

    /**
     * Get tier
     *
     * @return Tiers
     */
    public function getTier(): ?Tiers
    {
        return $this->tier;
    }

    /**
     * Add vente
     *
     * @param Vente $vente
     *
     * @return Facture
     */
    public function addVente(Vente $vente)
    {
        $this->ventes[] = $vente;

        $vente->setFacture($this);

        return $this;
    }

    /**
     * Remove vente
     *
     * @param Vente $vente
     */
    public function removeVente(Vente $vente)
    {
        $this->ventes->removeElement($vente);
    }

    /**
     * Get ventes
     *
     * @return Collection|Vente[]
     */
    public function getVentes()
    {
        return $this->ventes;
    }

    /**
     * Set scan
     *
     * @param Scan $scan
     *
     * @return Facture
     */
    public function setScan(Scan $scan = null)
    {
        $this->scan = $scan;

        return $this;
    }

    /**
     * Get scan
     *
     * @return Scan
     */
    public function getScan()
    {
        return $this->scan;
    }

    /**
     * @return float
     */
    public function getAutreProd()
    {
        return $this->autreProd;
    }

    /**
     * @param float $autreProd
     * @return Facture
     */
    public function setAutreProd($autreProd)
    {
        $this->autreProd = $autreProd;
        return $this;
    }



    /**
     * @return mixed
     */
    public function getIdLi()
    {
        return $this->id_li;
    }

    /**
     * @param mixed $id_li
     * @return Facture
     */
    public function setIdLi($id_li)
    {
        $this->id_li = $id_li;
        return $this;
    }


    /**
     * @return float
     */
    public function getMontatRembourse()
    {
        return $this->montatRembourse;
    }

    /**
     * @param float $montatRembourse
     * @return Facture
     */
    public function setMontatRembourse($montatRembourse)
    {
        $this->montatRembourse = $montatRembourse;
        return $this;
    }

    /**

src/Entity/Vente/FactureTrait.php
<?php
/**
 * Created by PhpStorm.
 * User: houlder
 * Date: 3/14/19
 * Time: 4:34 PM
 */

namespace App\Entity\Vente;


use App\Entity\Admin\LigneCompta;
use App\Entity\Admin\Tiers;
use App\Library\AsLetter;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Exception;

trait FactureTrait
{

    /**
     * @return mixed
     */
    public function getMontantNote()
    {
        return $this->getTotalPaiement() - $this->getTotalMontant();
    }

    /**
     * @return array
     */
    public function getVenteRemboursable()
    {
        $ventesReturn = array();
        /** @var Vente $item */
        foreach ($this->ventes as $item){
            if ($item->isRemboursable()){
                $ventesReturn[] = $item;
            }
        }
        return $ventesReturn;
    }

    /**
     * @return int
     */
    public function getRemboursable()
    {
        $montant = 0;

        /** @var ArrayCollection $lesVentes */
        $lesVentes = $this->getVentes();

        foreach ($lesVentes->getIterator() as $item){
            if ($item->isRemboursable()){
                $montant = $montant + $item->getTotalTarifBC();
            }
        }
        return $montant;
    }

    /**
     * @param bool $commission
     *
     * @return int
     */
    public function getTotalPaiement(bool $commission = true)
    {
        $montant = 0;
        $payements = $this->getPaiementFactures();
        /** @var PaiementFacture $pay */
        foreach ($payements as $pay){
            if ($commission) {
                $montant = $montant + (int)$pay->getTotalPaiement();
            } else {
                $montant = $montant + (int)$pay->getMontant();
            }
        }

        return (float) $montant;
    }

    public function getTotalMontant()
    {
        return (int)$this->getMontantTransport()
            +(int)$this->getMontantTaxe()
            +(int)$this->getMontantFees()
            +(int)$this->getMontantTva()
            + $this->getAutreProd();
    }

    public function getSolde($commission = true)
    {
        return $this->getTotalMontant() - $this->getTotalPaiement($commission);
    }

    /**
     *
     * @return string
     *
     */
    public function getLetter()
    {
        $text = AsLetter::asLetters($this->getTotalMontant());
        $text_explode = explode(' ', $text);
        if ($text_explode[0] == 'millions'){
            $text = 'un '.$text;
        }
        return $text;
    }

    /**
     * Check if facture totalement payé
     */
    public function checKSolde()
    {
        if ($this->getSolde() <= 0){
            $this->setPayed(true);
        }
    }
}

src/Entity/Vente/ScanRepository.php
<?php

namespace App\Entity\Vente;

use Doctrine\ORM\EntityRepository;

/**
 * ScanRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ScanRepository extends EntityRepository
{
}

src/Form/Vente/BCType.php
<?php
/**
 * Created by PhpStorm.
 * User: DEV
 * Date: 18/09/2017
 * Time: 09:28
 */

namespace App\Form\Vente;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BCType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @throws \Exception
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tier', EntityType::class, [
                'class' => 'App\Entity\Admin\Tiers',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->where('t.discriminator = ?1')
                        ->setParameter(1,'fournisseurs')
                        ->andWhere('t.linked = ?2')
                        ->setParameter('2',false);
                },
                'attr' => [
                    'class' => 'field'
                ],
                'label' => 'Fournisseurs'
            ])
            ->add('pnr', TextType::class, [
                'attr' => [
                    'class' => 'field'
                ],
                'label' => 'PNR'
            ])
            ->add('pnrPropre', TextType::class, [
                'label' => 'PNR propre'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Vente\BonCommande'
        ));
    }
}

src/Form/Vente/FactureType.php
<?php
/**
 * Created by PhpStorm.
 * User: DEV
 * Date: 04/09/2017
 * Time: 06:34
 */

namespace App\Form\Vente;

use DateTime;
use Exception;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactureType extends AbstractType
{

    /**
     *
     * @param FormBuilderInterface $builder
     * @param array $options
     * @throws Exception
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $today = new DateTime('now');
        $builder
            /*->add('tier', EntityType::class, [
                'class' => 'App\Entity\Admin\Tiers',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->where('t.discriminator = ?1')
                        ->setParameter(1,'client');
                },
                'attr' => [
                    'class' => 'field'
                ],
                'label' => 'Client'

            ])*/
            ->add('idLi', ChoiceType::class, [
                'choices'   => $options['cli_choice'],
                'attr' => [
                    'class' => 'field util',
                ],
                'label' => 'Client',
                'required'  => true,
            ])

            /*->add('tauxChange', TextType::class, [
                'attr' => [
                    'class' => 'field'
                ],
                'label'=> 'Taux de change'
            ])*/
            ->add('typePaiement', ChoiceType::class, [
                    'choices'   => array(
                        'A crédit' => 'credit',
                        'Au comptant' => 'comptant',

                    ),
                    'attr' => [
                        'class' => 'field util',
                    ],
                    'label' => 'Type de paiement',
                    'required'  => true,
            ])
            ->add('dateEcheance', DateType::class, [
                'attr' => [
                    'class' => 'acompte'
                ],
                'widget' => 'single_text',
                'label'  => 'Date d\'échéance',
                'data'   => $today->modify('+15 day')
            ])
            /*->add('paiements', CollectionType::class, [
                'entry_type'   => PaiementType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
                'attr' => [
                    'class' => 'my-selector',
                ],
            ])*/
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Vente\Facture',
            'cli_choice' => null,
        ));
    }
}

templates/vente/cli_ajax.html.twig
{% for client in clients %}
    <option value="{{ client.id }}" {% if client.id == id_cli %} selected {% endif %} >{{ client }}</option>
{% endfor %}
<option value="999999999" >Nouveau client</option>

templates/vente/edit.html.twig
{%
form_theme form
'parcour_theme.html.twig'
'form/my_theme.html.twig'
'jquery.collection.html.twig'
%}

{#{% set data_url = path('fees_show',{'id':'1'}) %}#}
{% set data_url = path('fees_show', {'id': '2'}) %}

{#{% set valeur = (vente is defined)? vente.devise:devise %}#}

{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if label == "danger" %}
            <script>
                $.notify({
                    // options
                    message: '{{ message }}'
                },{
                    // settings
                    type: '{{ label }}'
                });
            </script>
        {% endif %}
        {#<div class="flash-{{ label }}">
            {{ message }}
        </div>#}
    {% endfor %}
{% endfor %}

<div class="row">
    <div class="col-sm-3 text-info">
        <h3>
            {% autoescape false %}
                {{ form_titre }}
            {% endautoescape %}
        </h3>
    </div>
    <div class="col-sm-7 text-right" id="form_scan">
    </div>
</div>
<hr style="margin: 5px;">
<div class="row" id="list-mail">
    {{ form_start(form) }}
    <div class="col-sm-6">
        {{ form_row(form.typeBillet) }}
        {{ form_row(form.remboursable) }}
        {{ form_row(form.numBillet) }}
        {{ form_row(form.bookRef) }}
        {{ form_row(form.passager) }}
        {{ form_row(form.fees,{'attr':{'data-url': data_url }}) }}
        {{ form_row(form.classes) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.compagieAerienne) }}
        {{ form_row(form.currency) }}
        {{ form_row(form.feesAGV) }}
        {{ form_row(form.montantTransport) }}
        {{ form_row(form.taxe) }}
        {{ form_row(form.type) }}
        {{ form_row(form.autreFees) }}
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            <h5 class="text-muted grey" style="text-decoration: underline; margin: 5px !important;">Les itinéraires</h5>
            <div class="col-sm-12">
                {{ form_widget(form.parcours) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
    <div class="col-sm-12 text-center">
        <button class="btn btn-danger retour" data-cible="#list_vente"><i class="ace-icon fa fa-close"></i> &nbsp; Annuler</button>
        <button class="btn btn-primary" id="save_vente"><i class="ace-icon glyphicon glyphicon-check"></i> &nbsp; Valider</button>
    </div>
</div>
{#<div class="row text-center">
</div>#}
<script type="text/javascript">



    /*<script type="text/javascript">*/
    $('.my-selector').collection({
        min: 1,
        allow_up: false,
        allow_down: false,
        allow_duplicate: false,
        add: '<a href="#" class="btn btn-sm btn-primary"><i class="ace-icon fa fa-plus-circle"></i></a>',
        remove: '<a href="#" class="btn btn-sm btn-danger"><i class="ace-icon fa fa-minus-circle"></i></a>',
        init_with_n_elements: 1

    });
    $("#vente_autreFees").val('');
    $('#vente_fees').trigger('change');
    $('#vente_typeBillet').trigger('change');
    $("#vente_autreFees").val('0');

    /*$(".collection-actions").addClass('text-right');*/
</script>

templates/vente/facturer.html.twig

{%
form_theme form
'form/my_theme.html.twig'
'paiement_theme.html.twig'
'jquery.collection.html.twig'
%}


    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <script>
                $.notify({
                    // options
                    message: '{{ message }}'
                },{
                    // settings
                    type: '{{ label }}'
                });
            </script>
            {#<div class="flash-{{ label }}">
                {{ message }}
            </div>#}
        {% endfor %}
    {% endfor %}


<div class="row">

    {{ form_start(form) }}
    <div class="col-sm-6">
        <input type="hidden" name="idVentes" value="{{ idVentes }}">

        {{ form_row(form.idLi,{'attr':{'data-url': data_url }}) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.typePaiement) }}
        {{ form_row(form.dateEcheance) }}
    </div>
    {{ form_end(form) }}

    <script type="text/javascript">
        var change = undefined;

        /*$(document).on('change','#facture_paiements_0_moyenPay', function () {
            var value = $(this).val();
            if((value === "1") || (value === "4") ){
                console.log(value);
                $('.carte').removeClass('field').parent().parent('.form-group').hide();
                $('.cheque').removeClass('field').parent().parent('.form-group').hide();
                $('.devise').removeClass('field').parent().parent('.form-group').hide();
                /!*$('.cheque').removeClass('field').parent().parent('.form-group').hide();*!/
                $('.note-cred').removeClass('field').parent().parent('.form-group').hide();
            } else if (value === '2') {
                console.log(value);
                $('.carte').removeClass('field').parent().parent('.form-group').hide();
                $('.devise').removeClass('field').parent().parent('.form-group').hide();
                $('.note-cred').removeClass('field').parent().parent('.form-group').hide();
                $('.cheque').addClass('field').parent().parent('.form-group').show();
            } else if (value === '3') {
                console.log(value);
                $('.carte').addClass('field').parent().parent('.form-group').show();
                $('.cheque').removeClass('field').parent().parent('.form-group').hide();
                $('.devise').removeClass('field').parent().parent('.form-group').hide();
                $('.note-cred').removeClass('field').parent().parent('.form-group').hide();
            } else if (value === '5'){
                console.log(value);
                $('.carte').removeClass('field').parent().parent('.form-group').hide();
                $('.cheque').removeClass('field').parent().parent('.form-group').hide();
                /!*$('.cheque').removeClass('field').parent().parent('.form-group').hide();*!/
                $('.note-cred').removeClass('field').parent().parent('.form-group').hide();
                $('.devise').removeClass('field').parent().parent('.form-group').show();
            } else {
                console.log(value);
                $('.devise').removeClass('field').parent().parent('.form-group').hide();
                $('.carte').removeClass('field').parent().parent('.form-group').hide();
                $('.cheque').removeClass('field').parent().parent('.form-group').hide();
                $('.note-cred').removeClass('field').parent().parent('.form-group').show();
            }
        });*/
        $(document).on('change','#facture_typePaiement', function () {
            var value = $(this).val();
            if(value === "credit"){
                $('.acompte').parent().parent('.form-group').show();
            } else {
                $('.acompte').parent().parent('.form-group').hide();
            }
        });
        $('#facture_typePaiement').trigger('change');
        /*$('#facture_paiements_0_moyenPay').trigger('change');*/

    </script>



</div>

templates/vente/form_vente.html.twig
{%
form_theme form
'parcour_theme.html.twig'
'form/my_theme.html.twig'
'jquery.collection.html.twig'
%}

{#{% set data_url = path('fees_show',{'id':'1'}) %}#}
{% set data_url = path('fees_show', {'id': '2'}) %}

{#{% set valeur = (vente is defined)? vente.devise:devise %}#}

{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if label == "danger" %}
            <script>
                $.notify({
                    // options
                    message: '{{ message }}'
                },{
                    // settings
                    type: '{{ label }}'
                });
            </script>
        {% endif %}
        {#<div class="flash-{{ label }}">
            {{ message }}
        </div>#}
    {% endfor %}
{% endfor %}

<div class="row">
    <div class="col-sm-3 text-info">
        <h3>
            {% autoescape false %}
                {{ form_titre }}
            {% endautoescape %}
        </h3>
    </div>
    <div class="col-sm-7 text-right" id="form_scan">
        {{ form_start(scan_form) }}
        <div class="form-group">
            <label class="col-sm-5 control-label">Fichier à scanner (PDF)</label>
            <div class="col-sm-7 input-group">
                {{ form_widget(scan_form.file) }}
                <span class="input-group-btn">
                        <button id="valid_scan" class="btn btn-primary btn-sm">
                            <span class="fa fa-search"></span>
                            Scanner
                        </button>
                    </span>
            </div>
        </div>
        {{ form_end(scan_form) }}
    </div>
</div>
<hr style="margin: 5px;">
<div class="row" id="list-mail">
    {{ form_start(form) }}
    <div class="col-sm-6">
        {{ form_row(form.typeBillet) }}
        {{ form_row(form.remboursable) }}
        {{ form_row(form.numBillet) }}
        {{ form_row(form.bookRef) }}
        {{ form_row(form.passager) }}
        {{ form_row(form.fees,{'attr':{'data-url': data_url }}) }}
        {{ form_row(form.classes) }}
    </div>
    <div class="col-sm-6">
        {{ form_row(form.compagieAerienne) }}
        {{ form_row(form.currency) }}
        {{ form_row(form.montantTransport) }}
        {{ form_row(form.taxe) }}
        {{ form_row(form.type) }}
        {{ form_row(form.autreFees) }}
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            <h5 class="text-muted grey" style="text-decoration: underline; margin: 5px !important;">Les itinéraires</h5>
            <div class="col-sm-12">
                {{ form_widget(form.parcours) }}
            </div>
        </div>
    </div>

    {{ form_end(form) }}
    <div class="col-sm-12 text-center">
        <button class="btn btn-danger retour" data-cible="#list_vente"><i class="ace-icon fa fa-close"></i> &nbsp; Annuler</button>
        <button class="btn btn-primary" id="save_vente"><i class="ace-icon glyphicon glyphicon-check"></i> &nbsp; Valider</button>
    </div>
</div>
{#<div class="row text-center">
</div>#}
<script type="text/javascript">



/*<script type="text/javascript">*/
    $('.my-selector').collection({
        min: 1,
        allow_up: false,
        allow_down: false,
        allow_duplicate: false,
        add: '<a href="#" class="btn btn-sm btn-primary"><i class="ace-icon fa fa-plus-circle"></i></a>',
        remove: '<a href="#" class="btn btn-sm btn-danger"><i class="ace-icon fa fa-minus-circle"></i></a>',
        init_with_n_elements: 1

    });
    $("#vente_autreFees").val('');
    $('#vente_fees').trigger('change');
    $('#vente_typeBillet').trigger('change');
    $("#vente_autreFees").val('0');

    /*$(".collection-actions").addClass('text-right');*/
</script>

templates/vente/list-mail.html.twig
<div class="col-sm-12">
    <div class="col-sm-10">
        <h3><span class="ace-icon fa fa-envelope-square"></span>&nbsp;Les mails</h3>
    </div>
    <div class="col-sm-2 text-right">
        <button data-lien="{{ path('vente_nouveau') }}" class="btn btn-primary btn-sm scan">
            <i class="ace-icon fa fa-reply"></i>
            Retour au formulaire
        </button>
    </div>
</div>
<div class="col-sm-12">
    {% if inbox is null %}
        <div class="alert alert-warning">
            Le serveur n'es pas accessible pour le moment
        </div>
    {% else %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th width="20%">
                    Date
                </th>
                <th width="20%">
                    Expediteur
                </th>
                <th>
                    Objet
                </th>
                <th class="text-right" width="10%">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for mail in inbox %}
                <tr>
                    <td>
                        {{ mail.date|date }}
                    </td>
                    <td>
                        {% if mail.sender.personal is defined %}
                            {{ mail.sender.personal }}
                        {% else %}
                            {{ mail.sender.mailbox~'@'~mail.sender.host }}
                        {% endif %}
                    </td>
                    <td>
                        {{ mail.subject }}
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button data-lien="{{ path('vente _scan_mail',{'index': mail.index}) }}" class="btn btn-xs btn-info scan">
                                <i class="ace-icon fa fa-search-plus bigger-120"></i>&nbsp;Scanner
                            </button>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
</div>